logging:
  level:
    io:
      decontextualization:
        client: DEBUG
        spec: DEBUG

spring:
  application:
    name: spring-boot-ai-gemini-integration
  ai:
    openai:
      api-key: AIzaSyCmP6HiQcx6rimgAhlAIAc_ocCq0urgyig
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash-exp
server:
  port: 8080
